services:
  # 1. Redis Cache & Pub/Sub Message Broker (Local Bridge Mode)
  redis:
    image: redis:7.4-alpine
    container_name: drone-redis
    restart: unless-stopped
    ports:
      - "6380:6380"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes", "--port", "6380"]

  # 2. Go MAVLink Ingestion Service (Local Bridge Mode)
  telemetry-ingestion:
    build:
      context: ./telemetry-ingestion-service
      dockerfile: Dockerfile
    container_name: drone-telemetry-ingestion
    restart: unless-stopped
    ports:
      - "14551:14551/udp"
      - "10002:10002"
    depends_on:
      - redis
    environment:
      - UDP_LISTEN_ADDR=0.0.0.0:14551
      - TCP_GCS_PORT=10002
      - REDIS_ADDR=redis:6380
      - REDIS_DB=0
      - STATE_TTL_SECONDS=30
      - PUBLISH_INTERVAL_MS=100
      - VPN_SUBNET_PREFIX=10.13.37.

  # 3. NestJS API Gateway & Mission Control Dashboard (Local Bridge Mode)
  provisioning-api:
    build:
      context: ./provisioning-api
      dockerfile: Dockerfile
    container_name: drone-provisioning-api
    restart: unless-stopped
    ports:
      - "10004:10004"
    depends_on:
      - redis
    volumes:
      - ./data/db:/data
    environment:
      - DATABASE_URL=file:/data/provisioning.db
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - PORT=10004
      - PROVISION_SECRET_TOKEN=FACTORY_SECRET_KEY_2026
      - WG_SERVER_ENDPOINT=103.253.20.32:10006
      - WG_INTERFACE=wg0
      - VPN_SUBNET_PREFIX=10.13.37.
      - INTERNAL_MTX_HOST=media-server
      - INTERNAL_MTX_HLS_PORT=8888
      - INTERNAL_MTX_WHEP_PORT=10001
      - INTERNAL_MTX_RTSP_PORT=8554


  # 4. Ultra-Low Latency Video Streaming Server (MediaMTX - Local Bridge Mode)
  media-server:
    image: bluenviron/mediamtx:latest
    container_name: drone-media-server
    restart: unless-stopped
    ports:
      - "8554:8554"        # RTSP Ingest từ Drone
      - "10001:10001"      # WebRTC WHEP Egress cho Web Dashboard
      - "8888:8888"        # HLS Video Stream
    environment:
      - MTX_PROTOCOLS=tcp,udp
      - MTX_WEBRTCADDITIONALHOSTS=127.0.0.1
      - MTX_RTSPADDRESS=:8554
      - MTX_WEBRTCADDRESS=:10001
      - MTX_WEBRTCICETCPMUXADDRESS=:10005
      - MTX_HLSADDRESS=:8888
      - MTX_API=yes
      - MTX_APIADDRESS=:9997
