services:
  drone-fleet-manager:
    build: .
    container_name: drone-fleet-manager
    # BẮT BUỘC: Dùng chung mạng với Host VPS để cấu hình trực tiếp card mạng thật
    network_mode: "host"
    # BẮT BUỘC: Quyền Admin Mạng để được phép cấu hình WireGuard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
    environment:
      - PORT=10004
      - DATABASE_URL=postgresql://postgres:postgres_password@127.0.0.1:5432/provisioning_db?schema=public
      - ADMIN_DEFAULT_EMAIL=admin@gmail.com
      - ADMIN_DEFAULT_PASSWORD=admin
      - JWT_SECRET=super-secret-key-for-jwt-token-sbcloud-xblink
    env_file:
      - .env
    restart: unless-stopped
